#!/bin/bash

MASTER_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
TEMPLATES_DIR="${MASTER_DIR}/templates"

. ${TEMPLATES_DIR}/common.sh
source_host


if [ "$1" == "create" -o "$1" == "new" ]; then
    _new_vm "$2"
elif [ "$1" == "run" ]; then
    _run_vm "$2"
elif [ "$1" == "monitor" ]; then
    _monitor_vm "$2"
elif [ "$1" == "connect" -o "$1" == "ssh" ]; then
    _ssh_vm "$2"
elif [ "$1" == "status" ]; then
    _status_vm "$2"
else
    cat << EOF
Usage: ./vm command [arguments]

Commands:
    create   [template]     Create a new VM based off of a template
    run      [vm]           Start up a VM
    monitor  [vm]           Monitor and connect to the VM manager
    ssh      [vm]           Connect to the VM
    status   [vm]           Get the state of a VM
EOF
fi
